export const indianStates = [
  { value: '01', label: 'Jammu & Kashmir', code: '01', state: 'Jammu & Kashmir' },
  { value: '02', label: 'Himachal Pradesh', code: '02', state: 'Himachal Pradesh' },
  { value: '03', label: 'Punjab', code: '03', state: 'Punjab' },
  { value: '04', label: 'Chandigarh', code: '04', state: 'Chandigarh' },
  { value: '05', label: 'Uttarakhand', code: '05', state: 'Uttarakhand' },
  { value: '06', label: 'Haryana', code: '06', state: 'Haryana' },
  { value: '07', label: 'Delhi', code: '07', state: 'Delhi' },
  { value: '08', label: 'Rajasthan', code: '08', state: 'Rajasthan' },
  { value: '09', label: 'Uttar Pradesh', code: '09', state: 'Uttar Pradesh' },
  { value: '10', label: 'Bihar', code: '10', state: 'Bihar' },
  { value: '11', label: 'Sikkim', code: '11', state: 'Sikkim' },
  { value: '12', label: 'Arunachal Pradesh', code: '12', state: 'Arunachal Pradesh' },
  { value: '13', label: 'Nagaland', code: '13', state: 'Nagaland' },
  { value: '14', label: 'Manipur', code: '14', state: 'Manipur' },
  { value: '15', label: 'Mizoram', code: '15', state: 'Mizoram' },
  { value: '16', label: 'Tripura', code: '16', state: 'Tripura' },
  { value: '17', label: 'Meghalaya', code: '17', state: 'Meghalaya' },
  { value: '18', label: 'Assam', code: '18', state: 'Assam' },
  { value: '19', label: 'West Bengal', code: '19', state: 'West Bengal' },
  { value: '20', label: 'Jharkhand', code: '20', state: 'Jharkhand' },
  { value: '21', label: 'Odisha', code: '21', state: 'Odisha' },
  { value: '22', label: 'Chhattisgarh', code: '22', state: 'Chhattisgarh' },
  { value: '23', label: 'Madhya Pradesh', code: '23', state: 'Madhya Pradesh' },
  { value: '24', label: 'Gujarat', code: '24', state: 'Gujarat' },
  { value: '25', label: 'Daman & Diu', code: '25', state: 'Daman & Diu' },
  { value: '26', label: 'Dadra & Nagar Haveli', code: '26', state: 'Dadra & Nagar Haveli' },
  { value: '27', label: 'Maharashtra', code: '27', state: 'Maharashtra' },
  { value: '28', label: 'Andhra Pradesh (Old)', code: '28', state: 'Andhra Pradesh (Old)' },
  { value: '29', label: 'Karnataka', code: '29', state: 'Karnataka' },
  { value: '30', label: 'Goa', code: '30', state: 'Goa' },
  { value: '31', label: 'Lakshadweep', code: '31', state: 'Lakshadweep' },
  { value: '32', label: 'Kerala', code: '32', state: 'Kerala' },
  { value: '33', label: 'Tamil Nadu', code: '33', state: 'Tamil Nadu' },
  { value: '34', label: 'Puducherry', code: '34', state: 'Puducherry' },
  { value: '35', label: 'Andaman & Nicobar Islands', code: '35', state: 'Andaman & Nicobar Islands' },
  { value: '36', label: 'Telangana', code: '36', state: 'Telangana' },
  { value: '37', label: 'Andhra Pradesh (New)', code: '37', state: 'Andhra Pradesh (New)' },
  { value: '38', label: 'Ladakh', code: '38', state: 'Ladakh' },
];
