/**
 * State list per country with state codes.
 * India includes official GST state codes.
 * Other countries include ISO 3166-2 subdivision codes.
 */
export const statesByCountry = {
  IN: [
    { label: 'Andaman and Nicobar Islands', value: 'Andaman and Nicobar Islands', code: '35' },
    { label: 'Andhra Pradesh',              value: 'Andhra Pradesh',              code: '37' },
    { label: 'Arunachal Pradesh',           value: 'Arunachal Pradesh',           code: '12' },
    { label: 'Assam',                       value: 'Assam',                       code: '18' },
    { label: 'Bihar',                       value: 'Bihar',                       code: '10' },
    { label: 'Chandigarh',                  value: 'Chandigarh',                  code: '04' },
    { label: 'Chhattisgarh',               value: 'Chhattisgarh',               code: '22' },
    { label: 'Dadra and Nagar Haveli and Daman and Diu', value: 'Dadra and Nagar Haveli and Daman and Diu', code: '26' },
    { label: 'Delhi',                       value: 'Delhi',                       code: '07' },
    { label: 'Goa',                         value: 'Goa',                         code: '30' },
    { label: 'Gujarat',                     value: 'Gujarat',                     code: '24' },
    { label: 'Haryana',                     value: 'Haryana',                     code: '06' },
    { label: 'Himachal Pradesh',            value: 'Himachal Pradesh',            code: '02' },
    { label: 'Jammu and Kashmir',           value: 'Jammu and Kashmir',           code: '01' },
    { label: 'Jharkhand',                   value: 'Jharkhand',                   code: '20' },
    { label: 'Karnataka',                   value: 'Karnataka',                   code: '29' },
    { label: 'Kerala',                      value: 'Kerala',                      code: '32' },
    { label: 'Ladakh',                      value: 'Ladakh',                      code: '38' },
    { label: 'Lakshadweep',                 value: 'Lakshadweep',                 code: '31' },
    { label: 'Madhya Pradesh',              value: 'Madhya Pradesh',              code: '23' },
    { label: 'Maharashtra',                 value: 'Maharashtra',                 code: '27' },
    { label: 'Manipur',                     value: 'Manipur',                     code: '14' },
    { label: 'Meghalaya',                   value: 'Meghalaya',                   code: '17' },
    { label: 'Mizoram',                     value: 'Mizoram',                     code: '15' },
    { label: 'Nagaland',                    value: 'Nagaland',                    code: '13' },
    { label: 'Odisha',                      value: 'Odisha',                      code: '21' },
    { label: 'Puducherry',                  value: 'Puducherry',                  code: '34' },
    { label: 'Punjab',                      value: 'Punjab',                      code: '03' },
    { label: 'Rajasthan',                   value: 'Rajasthan',                   code: '08' },
    { label: 'Sikkim',                      value: 'Sikkim',                      code: '11' },
    { label: 'Tamil Nadu',                  value: 'Tamil Nadu',                  code: '33' },
    { label: 'Telangana',                   value: 'Telangana',                   code: '36' },
    { label: 'Tripura',                     value: 'Tripura',                     code: '16' },
    { label: 'Uttar Pradesh',               value: 'Uttar Pradesh',               code: '09' },
    { label: 'Uttarakhand',                 value: 'Uttarakhand',                 code: '05' },
    { label: 'West Bengal',                 value: 'West Bengal',                 code: '19' },
  ],
  US: [
    { label: 'Alabama',        value: 'Alabama',        code: 'AL' },
    { label: 'Alaska',         value: 'Alaska',         code: 'AK' },
    { label: 'Arizona',        value: 'Arizona',        code: 'AZ' },
    { label: 'Arkansas',       value: 'Arkansas',       code: 'AR' },
    { label: 'California',     value: 'California',     code: 'CA' },
    { label: 'Colorado',       value: 'Colorado',       code: 'CO' },
    { label: 'Connecticut',    value: 'Connecticut',    code: 'CT' },
    { label: 'Delaware',       value: 'Delaware',       code: 'DE' },
    { label: 'Florida',        value: 'Florida',        code: 'FL' },
    { label: 'Georgia',        value: 'Georgia',        code: 'GA' },
    { label: 'Hawaii',         value: 'Hawaii',         code: 'HI' },
    { label: 'Idaho',          value: 'Idaho',          code: 'ID' },
    { label: 'Illinois',       value: 'Illinois',       code: 'IL' },
    { label: 'Indiana',        value: 'Indiana',        code: 'IN' },
    { label: 'Iowa',           value: 'Iowa',           code: 'IA' },
    { label: 'Kansas',         value: 'Kansas',         code: 'KS' },
    { label: 'Kentucky',       value: 'Kentucky',       code: 'KY' },
    { label: 'Louisiana',      value: 'Louisiana',      code: 'LA' },
    { label: 'Maine',          value: 'Maine',          code: 'ME' },
    { label: 'Maryland',       value: 'Maryland',       code: 'MD' },
    { label: 'Massachusetts',  value: 'Massachusetts',  code: 'MA' },
    { label: 'Michigan',       value: 'Michigan',       code: 'MI' },
    { label: 'Minnesota',      value: 'Minnesota',      code: 'MN' },
    { label: 'Mississippi',    value: 'Mississippi',    code: 'MS' },
    { label: 'Missouri',       value: 'Missouri',       code: 'MO' },
    { label: 'Montana',        value: 'Montana',        code: 'MT' },
    { label: 'Nebraska',       value: 'Nebraska',       code: 'NE' },
    { label: 'Nevada',         value: 'Nevada',         code: 'NV' },
    { label: 'New Hampshire',  value: 'New Hampshire',  code: 'NH' },
    { label: 'New Jersey',     value: 'New Jersey',     code: 'NJ' },
    { label: 'New Mexico',     value: 'New Mexico',     code: 'NM' },
    { label: 'New York',       value: 'New York',       code: 'NY' },
    { label: 'North Carolina', value: 'North Carolina', code: 'NC' },
    { label: 'North Dakota',   value: 'North Dakota',   code: 'ND' },
    { label: 'Ohio',           value: 'Ohio',           code: 'OH' },
    { label: 'Oklahoma',       value: 'Oklahoma',       code: 'OK' },
    { label: 'Oregon',         value: 'Oregon',         code: 'OR' },
    { label: 'Pennsylvania',   value: 'Pennsylvania',   code: 'PA' },
    { label: 'Rhode Island',   value: 'Rhode Island',   code: 'RI' },
    { label: 'South Carolina', value: 'South Carolina', code: 'SC' },
    { label: 'South Dakota',   value: 'South Dakota',   code: 'SD' },
    { label: 'Tennessee',      value: 'Tennessee',      code: 'TN' },
    { label: 'Texas',          value: 'Texas',          code: 'TX' },
    { label: 'Utah',           value: 'Utah',           code: 'UT' },
    { label: 'Vermont',        value: 'Vermont',        code: 'VT' },
    { label: 'Virginia',       value: 'Virginia',       code: 'VA' },
    { label: 'Washington',     value: 'Washington',     code: 'WA' },
    { label: 'West Virginia',  value: 'West Virginia',  code: 'WV' },
    { label: 'Wisconsin',      value: 'Wisconsin',      code: 'WI' },
    { label: 'Wyoming',        value: 'Wyoming',        code: 'WY' },
  ],
  GB: [
    { label: 'England',          value: 'England',          code: 'ENG' },
    { label: 'Scotland',         value: 'Scotland',         code: 'SCT' },
    { label: 'Wales',            value: 'Wales',            code: 'WLS' },
    { label: 'Northern Ireland', value: 'Northern Ireland', code: 'NIR' },
  ],
  AU: [
    { label: 'Australian Capital Territory', value: 'Australian Capital Territory', code: 'ACT' },
    { label: 'New South Wales',              value: 'New South Wales',              code: 'NSW' },
    { label: 'Northern Territory',           value: 'Northern Territory',           code: 'NT'  },
    { label: 'Queensland',                   value: 'Queensland',                   code: 'QLD' },
    { label: 'South Australia',              value: 'South Australia',              code: 'SA'  },
    { label: 'Tasmania',                     value: 'Tasmania',                     code: 'TAS' },
    { label: 'Victoria',                     value: 'Victoria',                     code: 'VIC' },
    { label: 'Western Australia',            value: 'Western Australia',            code: 'WA'  },
  ],
  CA: [
    { label: 'Alberta',                  value: 'Alberta',                  code: 'AB' },
    { label: 'British Columbia',         value: 'British Columbia',         code: 'BC' },
    { label: 'Manitoba',                 value: 'Manitoba',                 code: 'MB' },
    { label: 'New Brunswick',            value: 'New Brunswick',            code: 'NB' },
    { label: 'Newfoundland and Labrador',value: 'Newfoundland and Labrador',code: 'NL' },
    { label: 'Northwest Territories',    value: 'Northwest Territories',    code: 'NT' },
    { label: 'Nova Scotia',              value: 'Nova Scotia',              code: 'NS' },
    { label: 'Nunavut',                  value: 'Nunavut',                  code: 'NU' },
    { label: 'Ontario',                  value: 'Ontario',                  code: 'ON' },
    { label: 'Prince Edward Island',     value: 'Prince Edward Island',     code: 'PE' },
    { label: 'Quebec',                   value: 'Quebec',                   code: 'QC' },
    { label: 'Saskatchewan',             value: 'Saskatchewan',             code: 'SK' },
    { label: 'Yukon',                    value: 'Yukon',                    code: 'YT' },
  ],
  DE: [
    { label: 'Baden-Württemberg',        value: 'Baden-Württemberg',        code: 'BW' },
    { label: 'Bavaria',                  value: 'Bavaria',                  code: 'BY' },
    { label: 'Berlin',                   value: 'Berlin',                   code: 'BE' },
    { label: 'Brandenburg',              value: 'Brandenburg',              code: 'BB' },
    { label: 'Bremen',                   value: 'Bremen',                   code: 'HB' },
    { label: 'Hamburg',                  value: 'Hamburg',                  code: 'HH' },
    { label: 'Hesse',                    value: 'Hesse',                    code: 'HE' },
    { label: 'Lower Saxony',             value: 'Lower Saxony',             code: 'NI' },
    { label: 'Mecklenburg-Vorpommern',   value: 'Mecklenburg-Vorpommern',   code: 'MV' },
    { label: 'North Rhine-Westphalia',   value: 'North Rhine-Westphalia',   code: 'NW' },
    { label: 'Rhineland-Palatinate',     value: 'Rhineland-Palatinate',     code: 'RP' },
    { label: 'Saarland',                 value: 'Saarland',                 code: 'SL' },
    { label: 'Saxony',                   value: 'Saxony',                   code: 'SN' },
    { label: 'Saxony-Anhalt',            value: 'Saxony-Anhalt',            code: 'ST' },
    { label: 'Schleswig-Holstein',       value: 'Schleswig-Holstein',       code: 'SH' },
    { label: 'Thuringia',                value: 'Thuringia',                code: 'TH' },
  ],
  AE: [
    { label: 'Abu Dhabi',    value: 'Abu Dhabi',    code: 'AZ' },
    { label: 'Ajman',        value: 'Ajman',        code: 'AJ' },
    { label: 'Dubai',        value: 'Dubai',        code: 'DU' },
    { label: 'Fujairah',     value: 'Fujairah',     code: 'FU' },
    { label: 'Ras al-Khaimah', value: 'Ras al-Khaimah', code: 'RK' },
    { label: 'Sharjah',      value: 'Sharjah',      code: 'SH' },
    { label: 'Umm al-Quwain',value: 'Umm al-Quwain',code: 'UQ' },
  ],
};

/**
 * Get states for a given country code.
 * Returns empty array if country has no state data.
 */
export function getStatesByCountry(countryCode) {
  return statesByCountry[countryCode] || [];
}

/**
 * Get state code from state name + country code.
 */
export function getStateCode(countryCode, stateName) {
  const states = getStatesByCountry(countryCode);
  const found = states.find(
    (s) => s.value === stateName || s.label === stateName
  );
  return found ? found.code : '';
}
